/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as MissoesAdminRouteImport } from './routes/missoes-admin'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VideosNovaRouteImport } from './routes/videos.nova'
import { Route as ClientesNovaRouteImport } from './routes/clientes.nova'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AppVideosRouteImport } from './routes/app.videos'
import { Route as AppVacuumRouteImport } from './routes/app.vacuum'
import { Route as AppTreinoRouteImport } from './routes/app.treino'
import { Route as AppPulsoRouteImport } from './routes/app.pulso'
import { Route as AppPrivacidadeRouteImport } from './routes/app.privacidade'
import { Route as AppPremiosRouteImport } from './routes/app.premios'
import { Route as AppPassaporteRouteImport } from './routes/app.passaporte'
import { Route as AppNutricaoRouteImport } from './routes/app.nutricao'
import { Route as AppMissoesRouteImport } from './routes/app.missoes'
import { Route as AppFotosRouteImport } from './routes/app.fotos'
import { Route as AppFalarRouteImport } from './routes/app.falar'
import { Route as AppCartasRouteImport } from './routes/app.cartas'
import { Route as AppAjudaRouteImport } from './routes/app.ajuda'
import { Route as AppAguaRouteImport } from './routes/app.agua'
import { Route as AppVacuumIndexRouteImport } from './routes/app.vacuum.index'
import { Route as TreinosClienteClientIdRouteImport } from './routes/treinos.cliente.$clientId'
import { Route as ClientesIdPremiosRouteImport } from './routes/clientes.$id.premios'
import { Route as ClientesIdMissoesRouteImport } from './routes/clientes.$id.missoes'
import { Route as ClientesIdConteudosRouteImport } from './routes/clientes.$id.conteudos'
import { Route as AppVacuumTreinoRouteImport } from './routes/app.vacuum.treino'
import { Route as ApiPublicMateriaisTreinoRouteImport } from './routes/api/public/materiais/treino'
import { Route as ApiPublicHooksMaterializeDailyMissionsRouteImport } from './routes/api/public/hooks/materialize-daily-missions'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesAdminRoute = MissoesAdminRouteImport.update({
  id: '/missoes-admin',
  path: '/missoes-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VideosNovaRoute = VideosNovaRouteImport.update({
  id: '/videos/nova',
  path: '/videos/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovaRoute = ClientesNovaRouteImport.update({
  id: '/clientes/nova',
  path: '/clientes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppVacuumRoute = AppVacuumRouteImport.update({
  id: '/vacuum',
  path: '/vacuum',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoRoute = AppTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AppRoute,
} as any)
const AppPulsoRoute = AppPulsoRouteImport.update({
  id: '/pulso',
  path: '/pulso',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacidadeRoute = AppPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiosRoute = AppPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AppRoute,
} as any)
const AppPassaporteRoute = AppPassaporteRouteImport.update({
  id: '/passaporte',
  path: '/passaporte',
  getParentRoute: () => AppRoute,
} as any)
const AppNutricaoRoute = AppNutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFotosRoute = AppFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => AppRoute,
} as any)
const AppFalarRoute = AppFalarRouteImport.update({
  id: '/falar',
  path: '/falar',
  getParentRoute: () => AppRoute,
} as any)
const AppCartasRoute = AppCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AppRoute,
} as any)
const AppAjudaRoute = AppAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AppRoute,
} as any)
const AppAguaRoute = AppAguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => AppRoute,
} as any)
const AppVacuumIndexRoute = AppVacuumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVacuumRoute,
} as any)
const TreinosClienteClientIdRoute = TreinosClienteClientIdRouteImport.update({
  id: '/treinos/cliente/$clientId',
  path: '/treinos/cliente/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdPremiosRoute = ClientesIdPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => ClientesIdRoute,
} as any)
const ClientesIdMissoesRoute = ClientesIdMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => ClientesIdRoute,
} as any)
const ClientesIdConteudosRoute = ClientesIdConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => ClientesIdRoute,
} as any)
const AppVacuumTreinoRoute = AppVacuumTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AppVacuumRoute,
} as any)
const ApiPublicMateriaisTreinoRoute =
  ApiPublicMateriaisTreinoRouteImport.update({
    id: '/api/public/materiais/treino',
    path: '/api/public/materiais/treino',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMaterializeDailyMissionsRoute =
  ApiPublicHooksMaterializeDailyMissionsRouteImport.update({
    id: '/api/public/hooks/materialize-daily-missions',
    path: '/api/public/hooks/materialize-daily-missions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/missoes-admin': typeof MissoesAdminRoute
  '/premios': typeof PremiosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agua': typeof AppAguaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cartas': typeof AppCartasRoute
  '/app/falar': typeof AppFalarRoute
  '/app/fotos': typeof AppFotosRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/passaporte': typeof AppPassaporteRoute
  '/app/premios': typeof AppPremiosRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/pulso': typeof AppPulsoRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/vacuum': typeof AppVacuumRouteWithChildren
  '/app/videos': typeof AppVideosRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/nova': typeof ClientesNovaRoute
  '/videos/nova': typeof VideosNovaRoute
  '/app/': typeof AppIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/app/vacuum/treino': typeof AppVacuumTreinoRoute
  '/clientes/$id/conteudos': typeof ClientesIdConteudosRoute
  '/clientes/$id/missoes': typeof ClientesIdMissoesRoute
  '/clientes/$id/premios': typeof ClientesIdPremiosRoute
  '/treinos/cliente/$clientId': typeof TreinosClienteClientIdRoute
  '/app/vacuum/': typeof AppVacuumIndexRoute
  '/api/public/hooks/materialize-daily-missions': typeof ApiPublicHooksMaterializeDailyMissionsRoute
  '/api/public/materiais/treino': typeof ApiPublicMateriaisTreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/missoes-admin': typeof MissoesAdminRoute
  '/premios': typeof PremiosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agua': typeof AppAguaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cartas': typeof AppCartasRoute
  '/app/falar': typeof AppFalarRoute
  '/app/fotos': typeof AppFotosRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/passaporte': typeof AppPassaporteRoute
  '/app/premios': typeof AppPremiosRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/pulso': typeof AppPulsoRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/videos': typeof AppVideosRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/nova': typeof ClientesNovaRoute
  '/videos/nova': typeof VideosNovaRoute
  '/app': typeof AppIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/app/vacuum/treino': typeof AppVacuumTreinoRoute
  '/clientes/$id/conteudos': typeof ClientesIdConteudosRoute
  '/clientes/$id/missoes': typeof ClientesIdMissoesRoute
  '/clientes/$id/premios': typeof ClientesIdPremiosRoute
  '/treinos/cliente/$clientId': typeof TreinosClienteClientIdRoute
  '/app/vacuum': typeof AppVacuumIndexRoute
  '/api/public/hooks/materialize-daily-missions': typeof ApiPublicHooksMaterializeDailyMissionsRoute
  '/api/public/materiais/treino': typeof ApiPublicMateriaisTreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/missoes-admin': typeof MissoesAdminRoute
  '/premios': typeof PremiosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agua': typeof AppAguaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cartas': typeof AppCartasRoute
  '/app/falar': typeof AppFalarRoute
  '/app/fotos': typeof AppFotosRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/passaporte': typeof AppPassaporteRoute
  '/app/premios': typeof AppPremiosRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/pulso': typeof AppPulsoRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/vacuum': typeof AppVacuumRouteWithChildren
  '/app/videos': typeof AppVideosRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/nova': typeof ClientesNovaRoute
  '/videos/nova': typeof VideosNovaRoute
  '/app/': typeof AppIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/app/vacuum/treino': typeof AppVacuumTreinoRoute
  '/clientes/$id/conteudos': typeof ClientesIdConteudosRoute
  '/clientes/$id/missoes': typeof ClientesIdMissoesRoute
  '/clientes/$id/premios': typeof ClientesIdPremiosRoute
  '/treinos/cliente/$clientId': typeof TreinosClienteClientIdRoute
  '/app/vacuum/': typeof AppVacuumIndexRoute
  '/api/public/hooks/materialize-daily-missions': typeof ApiPublicHooksMaterializeDailyMissionsRoute
  '/api/public/materiais/treino': typeof ApiPublicMateriaisTreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/app'
    | '/aprovacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/exercicios'
    | '/lgpd'
    | '/login'
    | '/mensagens'
    | '/missoes-admin'
    | '/premios'
    | '/relatorios'
    | '/reset-password'
    | '/trocar-senha'
    | '/app/agua'
    | '/app/ajuda'
    | '/app/cartas'
    | '/app/falar'
    | '/app/fotos'
    | '/app/missoes'
    | '/app/nutricao'
    | '/app/passaporte'
    | '/app/premios'
    | '/app/privacidade'
    | '/app/pulso'
    | '/app/treino'
    | '/app/vacuum'
    | '/app/videos'
    | '/clientes/$id'
    | '/clientes/nova'
    | '/videos/nova'
    | '/app/'
    | '/clientes/'
    | '/videos/'
    | '/app/vacuum/treino'
    | '/clientes/$id/conteudos'
    | '/clientes/$id/missoes'
    | '/clientes/$id/premios'
    | '/treinos/cliente/$clientId'
    | '/app/vacuum/'
    | '/api/public/hooks/materialize-daily-missions'
    | '/api/public/materiais/treino'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/aprovacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/exercicios'
    | '/lgpd'
    | '/login'
    | '/mensagens'
    | '/missoes-admin'
    | '/premios'
    | '/relatorios'
    | '/reset-password'
    | '/trocar-senha'
    | '/app/agua'
    | '/app/ajuda'
    | '/app/cartas'
    | '/app/falar'
    | '/app/fotos'
    | '/app/missoes'
    | '/app/nutricao'
    | '/app/passaporte'
    | '/app/premios'
    | '/app/privacidade'
    | '/app/pulso'
    | '/app/treino'
    | '/app/videos'
    | '/clientes/$id'
    | '/clientes/nova'
    | '/videos/nova'
    | '/app'
    | '/clientes'
    | '/videos'
    | '/app/vacuum/treino'
    | '/clientes/$id/conteudos'
    | '/clientes/$id/missoes'
    | '/clientes/$id/premios'
    | '/treinos/cliente/$clientId'
    | '/app/vacuum'
    | '/api/public/hooks/materialize-daily-missions'
    | '/api/public/materiais/treino'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/app'
    | '/aprovacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/exercicios'
    | '/lgpd'
    | '/login'
    | '/mensagens'
    | '/missoes-admin'
    | '/premios'
    | '/relatorios'
    | '/reset-password'
    | '/trocar-senha'
    | '/app/agua'
    | '/app/ajuda'
    | '/app/cartas'
    | '/app/falar'
    | '/app/fotos'
    | '/app/missoes'
    | '/app/nutricao'
    | '/app/passaporte'
    | '/app/premios'
    | '/app/privacidade'
    | '/app/pulso'
    | '/app/treino'
    | '/app/vacuum'
    | '/app/videos'
    | '/clientes/$id'
    | '/clientes/nova'
    | '/videos/nova'
    | '/app/'
    | '/clientes/'
    | '/videos/'
    | '/app/vacuum/treino'
    | '/clientes/$id/conteudos'
    | '/clientes/$id/missoes'
    | '/clientes/$id/premios'
    | '/treinos/cliente/$clientId'
    | '/app/vacuum/'
    | '/api/public/hooks/materialize-daily-missions'
    | '/api/public/materiais/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AppRoute: typeof AppRouteWithChildren
  AprovacoesRoute: typeof AprovacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  ExerciciosRoute: typeof ExerciciosRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRoute
  MissoesAdminRoute: typeof MissoesAdminRoute
  PremiosRoute: typeof PremiosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  ClientesIdRoute: typeof ClientesIdRouteWithChildren
  ClientesNovaRoute: typeof ClientesNovaRoute
  VideosNovaRoute: typeof VideosNovaRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  TreinosClienteClientIdRoute: typeof TreinosClienteClientIdRoute
  ApiPublicHooksMaterializeDailyMissionsRoute: typeof ApiPublicHooksMaterializeDailyMissionsRoute
  ApiPublicMateriaisTreinoRoute: typeof ApiPublicMateriaisTreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes-admin': {
      id: '/missoes-admin'
      path: '/missoes-admin'
      fullPath: '/missoes-admin'
      preLoaderRoute: typeof MissoesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/videos/nova': {
      id: '/videos/nova'
      path: '/videos/nova'
      fullPath: '/videos/nova'
      preLoaderRoute: typeof VideosNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/nova': {
      id: '/clientes/nova'
      path: '/clientes/nova'
      fullPath: '/clientes/nova'
      preLoaderRoute: typeof ClientesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/videos': {
      id: '/app/videos'
      path: '/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacuum': {
      id: '/app/vacuum'
      path: '/vacuum'
      fullPath: '/app/vacuum'
      preLoaderRoute: typeof AppVacuumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treino': {
      id: '/app/treino'
      path: '/treino'
      fullPath: '/app/treino'
      preLoaderRoute: typeof AppTreinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pulso': {
      id: '/app/pulso'
      path: '/pulso'
      fullPath: '/app/pulso'
      preLoaderRoute: typeof AppPulsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacidade': {
      id: '/app/privacidade'
      path: '/privacidade'
      fullPath: '/app/privacidade'
      preLoaderRoute: typeof AppPrivacidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premios': {
      id: '/app/premios'
      path: '/premios'
      fullPath: '/app/premios'
      preLoaderRoute: typeof AppPremiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passaporte': {
      id: '/app/passaporte'
      path: '/passaporte'
      fullPath: '/app/passaporte'
      preLoaderRoute: typeof AppPassaporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutricao': {
      id: '/app/nutricao'
      path: '/nutricao'
      fullPath: '/app/nutricao'
      preLoaderRoute: typeof AppNutricaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missoes': {
      id: '/app/missoes'
      path: '/missoes'
      fullPath: '/app/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fotos': {
      id: '/app/fotos'
      path: '/fotos'
      fullPath: '/app/fotos'
      preLoaderRoute: typeof AppFotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/falar': {
      id: '/app/falar'
      path: '/falar'
      fullPath: '/app/falar'
      preLoaderRoute: typeof AppFalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartas': {
      id: '/app/cartas'
      path: '/cartas'
      fullPath: '/app/cartas'
      preLoaderRoute: typeof AppCartasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajuda': {
      id: '/app/ajuda'
      path: '/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AppAjudaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agua': {
      id: '/app/agua'
      path: '/agua'
      fullPath: '/app/agua'
      preLoaderRoute: typeof AppAguaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacuum/': {
      id: '/app/vacuum/'
      path: '/'
      fullPath: '/app/vacuum/'
      preLoaderRoute: typeof AppVacuumIndexRouteImport
      parentRoute: typeof AppVacuumRoute
    }
    '/treinos/cliente/$clientId': {
      id: '/treinos/cliente/$clientId'
      path: '/treinos/cliente/$clientId'
      fullPath: '/treinos/cliente/$clientId'
      preLoaderRoute: typeof TreinosClienteClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id/premios': {
      id: '/clientes/$id/premios'
      path: '/premios'
      fullPath: '/clientes/$id/premios'
      preLoaderRoute: typeof ClientesIdPremiosRouteImport
      parentRoute: typeof ClientesIdRoute
    }
    '/clientes/$id/missoes': {
      id: '/clientes/$id/missoes'
      path: '/missoes'
      fullPath: '/clientes/$id/missoes'
      preLoaderRoute: typeof ClientesIdMissoesRouteImport
      parentRoute: typeof ClientesIdRoute
    }
    '/clientes/$id/conteudos': {
      id: '/clientes/$id/conteudos'
      path: '/conteudos'
      fullPath: '/clientes/$id/conteudos'
      preLoaderRoute: typeof ClientesIdConteudosRouteImport
      parentRoute: typeof ClientesIdRoute
    }
    '/app/vacuum/treino': {
      id: '/app/vacuum/treino'
      path: '/treino'
      fullPath: '/app/vacuum/treino'
      preLoaderRoute: typeof AppVacuumTreinoRouteImport
      parentRoute: typeof AppVacuumRoute
    }
    '/api/public/materiais/treino': {
      id: '/api/public/materiais/treino'
      path: '/api/public/materiais/treino'
      fullPath: '/api/public/materiais/treino'
      preLoaderRoute: typeof ApiPublicMateriaisTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/materialize-daily-missions': {
      id: '/api/public/hooks/materialize-daily-missions'
      path: '/api/public/hooks/materialize-daily-missions'
      fullPath: '/api/public/hooks/materialize-daily-missions'
      preLoaderRoute: typeof ApiPublicHooksMaterializeDailyMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppVacuumRouteChildren {
  AppVacuumTreinoRoute: typeof AppVacuumTreinoRoute
  AppVacuumIndexRoute: typeof AppVacuumIndexRoute
}

const AppVacuumRouteChildren: AppVacuumRouteChildren = {
  AppVacuumTreinoRoute: AppVacuumTreinoRoute,
  AppVacuumIndexRoute: AppVacuumIndexRoute,
}

const AppVacuumRouteWithChildren = AppVacuumRoute._addFileChildren(
  AppVacuumRouteChildren,
)

interface AppRouteChildren {
  AppAguaRoute: typeof AppAguaRoute
  AppAjudaRoute: typeof AppAjudaRoute
  AppCartasRoute: typeof AppCartasRoute
  AppFalarRoute: typeof AppFalarRoute
  AppFotosRoute: typeof AppFotosRoute
  AppMissoesRoute: typeof AppMissoesRoute
  AppNutricaoRoute: typeof AppNutricaoRoute
  AppPassaporteRoute: typeof AppPassaporteRoute
  AppPremiosRoute: typeof AppPremiosRoute
  AppPrivacidadeRoute: typeof AppPrivacidadeRoute
  AppPulsoRoute: typeof AppPulsoRoute
  AppTreinoRoute: typeof AppTreinoRoute
  AppVacuumRoute: typeof AppVacuumRouteWithChildren
  AppVideosRoute: typeof AppVideosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAguaRoute: AppAguaRoute,
  AppAjudaRoute: AppAjudaRoute,
  AppCartasRoute: AppCartasRoute,
  AppFalarRoute: AppFalarRoute,
  AppFotosRoute: AppFotosRoute,
  AppMissoesRoute: AppMissoesRoute,
  AppNutricaoRoute: AppNutricaoRoute,
  AppPassaporteRoute: AppPassaporteRoute,
  AppPremiosRoute: AppPremiosRoute,
  AppPrivacidadeRoute: AppPrivacidadeRoute,
  AppPulsoRoute: AppPulsoRoute,
  AppTreinoRoute: AppTreinoRoute,
  AppVacuumRoute: AppVacuumRouteWithChildren,
  AppVideosRoute: AppVideosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClientesIdRouteChildren {
  ClientesIdConteudosRoute: typeof ClientesIdConteudosRoute
  ClientesIdMissoesRoute: typeof ClientesIdMissoesRoute
  ClientesIdPremiosRoute: typeof ClientesIdPremiosRoute
}

const ClientesIdRouteChildren: ClientesIdRouteChildren = {
  ClientesIdConteudosRoute: ClientesIdConteudosRoute,
  ClientesIdMissoesRoute: ClientesIdMissoesRoute,
  ClientesIdPremiosRoute: ClientesIdPremiosRoute,
}

const ClientesIdRouteWithChildren = ClientesIdRoute._addFileChildren(
  ClientesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AppRoute: AppRouteWithChildren,
  AprovacoesRoute: AprovacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  ExerciciosRoute: ExerciciosRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRoute,
  MissoesAdminRoute: MissoesAdminRoute,
  PremiosRoute: PremiosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  ClientesIdRoute: ClientesIdRouteWithChildren,
  ClientesNovaRoute: ClientesNovaRoute,
  VideosNovaRoute: VideosNovaRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  TreinosClienteClientIdRoute: TreinosClienteClientIdRoute,
  ApiPublicHooksMaterializeDailyMissionsRoute:
    ApiPublicHooksMaterializeDailyMissionsRoute,
  ApiPublicMateriaisTreinoRoute: ApiPublicMateriaisTreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
